name: amplitude_flutter_example
description: Demonstrates how to use the amplitude_flutter plugin.
publish_to: 'none'
version: 0.12.4

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  amplitude_flutter: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
