name: amplitude_flutter_example
description: Demonstrates how to use the amplitude_flutter plugin.
publish_to: 'none'
version: 0.12.4

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  amplitude_flutter:
    path: ../

flutter:
  uses-material-design: true
