name: amplitude_flutter
description: A new flutter plugin project.
version: 0.0.1
author:
homepage: https://github.com/amplitude/Amplitude-Flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info: "^0.4.0+1"
  http: "^0.12.0+2"
  crypto: "^2.0.6"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: "4.0.0"

flutter:
  plugin:
    androidPackage: com.amplitude.amplitude_flutter
    pluginClass: AmplitudeFlutterPlugin